---
title: "Hoeyetal2021"
output: html_document
---

```{r Load and Wrangle Data}
library(tidyverse)
library(brms)
library(emmeans)
library(gridExtra)
library(tidybayes)

dat.prop = read.csv("Data/Propagules.csv") %>%
  mutate(Treatment = recode(Treatment, caged = "Caged", exposed = "Exposed"),
         Habitat = recode(Habitat, crest ="Reef crest", flat ="Reef flat"),
         Site= recode(Site, bird = "Site 1", south= "Site 2"))
```

```{r Part 1 - Propagule Survival}
m1priors = get_prior(formula =proportion.remaining ~ Treatment*Habitat + Site, 
                    data=dat.prop, family="gamma")
mod.brms.surv = brm(formula =proportion.remaining ~ Treatment*Habitat + Site, 
                    data=dat.prop, family="gamma", sample_prior = T,
                    prior = c(prior(normal(0, 5), class = "Intercept"),
                              prior(normal(0, 5), class = "b"), 
                              prior(gamma(0.1, 0.1), class = "shape")),
                    warmup = 200, iter = 2000, chains = 3, cores = 3, thin=2
                    # control = list(adapt_delta = 0.995,
                    #                max_treedepth=15)
                    )
# perf.brms1 = performance::check_model(mod.brms.surv)
summary(mod.brms.surv)
p1 = dat.prop %>%
  modelr::data_grid(Treatment, Habitat, Site) %>%
  add_fitted_draws(mod.brms.surv, re_formula = NULL, scale = "response") 
p2 = dat.prop %>%
  modelr::data_grid(Treatment, Habitat, Site) %>%
  add_fitted_draws(mod.brms.surv, re_formula = NULL, scale = "response") %>%
  compare_levels(.value, by = Treatment) 
p1 = ggplot(p1, aes(y = .value, x = Site, fill = Treatment)) +
  theme_bw(base_size = 12) + 
  geom_point(data=dat.prop, aes(y=proportion.remaining, x=Site, colour=Treatment), position = position_jitterdodge(),pch=1) +
  stat_eye(alpha=0.7, position = position_dodge(width = 0.7)) + 
  scale_y_continuous(breaks = c(0.25, 0.5,0.75,1,1.25,1.5)) +
  theme(legend.position = "bottom",axis.title.x = element_blank(),
        legend.margin=margin(-10, 0, 0, 0)) +facet_grid(~Habitat) +
  ylab("Proportion of progagules remaining")   

p2 = ggplot(p2, aes(x = -.value, y = Site)) +
  stat_pointinterval(alpha=0.7, position = position_dodge(width = 0.7)) + 
  theme_bw(base_size = 12) + geom_vline(xintercept=0, linetype="dashed") +
  # scale_y_continuous(breaks = c(0.25, 0.5,0.75,1,1.25), limits = c(0.25,1.5)) +
  scale_y_discrete(limits=rev) +
  theme(legend.position = "right", axis.title.y = element_blank(),
        legend.margin=margin(-5, 0, 0, 0)) +facet_wrap(~Habitat, ncol = 1) +
  xlab("Difference in proportion of propagules \nremaining (Caged-Exposed)") 
g=egg::ggarrange(p1, p2, ncol=2, widths = c(1.4,1))
ggsave("Figures/PropSurvival.png", plot = g, device = "png", 
       width = 8, height = 5, dpi=300)
ggsave("Figures/PropSurvival.tiff", plot = g, device = "tiff", 
       width = 8, height = 5, dpi=300)
ggsave("Figures/PropSurvival.svg", plot = g, device = "svg", 
       width = 8, height = 5, dpi=300)
emmeans::emmeans(mod.brms.surv,~ Treatment*Habitat+Site, type="response")
```


```{r Part 2 - Grazing}
dat.bites = read.csv("Data/Chapter 5 fish bites.csv") %>%
  mutate(habitat = recode(habitat, Crest ="Reef crest", Flat ="Reef flat"),
         site= recode(site, Bird = "Site 1", South= "Site 2"))
colnames(dat.bites)[1] = "Date"
dat.bites.sum = dat.bites %>% 
  # filter(!is.na(bites)) %>%
  group_by(Date, id, habitat, site, bite_on) %>%
  summarise(TotalBites = sum(bites, na.rm =T)) %>%
  mutate(id = factor(id), bite_on = factor(bite_on)) %>%
  spread(bite_on,TotalBites) %>% 
  select(-V3) %>%
  gather(bite_on, TotalBites, 5:6, na.rm = F) %>% arrange(Date, id, habitat, site) %>%
  dplyr::mutate(TotalBites = replace_na(TotalBites, 0)) %>%
  mutate(TotalBites = round(TotalBites/3,0)) %>%
  mutate(habitat = factor(ifelse(habitat == "Reef crest", "Crest", "Flat"), 
                           levels = c("Crest", "Flat")))
sum2 = dat.bites.sum %>% group_by(habitat,bite_on, site) %>% summarise(mean = mean(TotalBites), se = sd((TotalBites)/sqrt(n())))

sum2 = dat.bites.sum %>% group_by(habitat,bite_on, site) %>% summarise(mean = mean(TotalBites), se = sd((TotalBites)/sqrt(n())))




ggplot(dat.bites.sum, aes(x=site, y=Bites.hr, fill = bite_on)) +
  geom_boxplot() + facet_wrap(~habitat)
m1priors = get_prior(formula =TotalBites ~ bite_on*habitat*site + (1|id/Date), 
                    data=dat.bites.sum, family="negbinomial")
mod.brms.bites = brm(formula =TotalBites ~ bite_on*habitat +habitat*site  + (1|id/Date), 
                    data=dat.bites.sum, family="negbinomial", sample_prior = T,
                    # prior = m1priors,
                    prior = c(prior(normal(0, 5), class = "Intercept"),
                              prior(normal(0, 5), class = "b"),
                              prior(normal(0,5), class = "sd"),
                              prior(gamma(0.1, 0.1), class = "shape")),
                    warmup = 200, iter = 2000, chains = 3, cores = 3, thin=2
                    # control = list(adapt_delta = 0.995,
                    #                max_treedepth=15)
                    )

mod.brms.bites3 = brm(formula =TotalBites ~ bite_on*habitat +site*habitat + (1|Date), 
                    data=dat.bites.sum, family="negbinomial", sample_prior = T,
                    # prior = m1priors,
                    prior = c(prior(normal(0, 5), class = "Intercept"),
                              prior(normal(0, 5), class = "b"),
                              prior(student_t(3, 0, 2.5), class = "sd"),
                              prior(gamma(0.1, 0.1), class = "shape")),
                    warmup = 200, iter = 2000, chains = 3, cores = 3, thin=2,
                    control = list(adapt_delta = 0.98)
                    #                max_treedepth=15)
                    )




mod.brm1 = add_criterion(mod.brms.bites,  "waic")
mod.brm3 = add_criterion(mod.brms.bites3,  "waic")
loo::loo_compare(mod.brm1,  mod.brm3, criterion = "waic")
waic(mod.brm1, mod.brm3)
emmeans::emmeans(mod.brms.bites,~ bite_on|habitat + site, type="response")
emmeans::emmeans(mod.brms.bites3,~ bite_on|habitat + site, type="response")
mod_embites = emmeans::emmeans(mod.brms.bites3,~ bite_on|habitat + site, type="response")
multcomp::cld(mod_embites)

p3a = dat.bites.sum %>%
  modelr::data_grid(bite_on, habitat, site) %>%
  add_fitted_draws(mod.brms.bites, re_formula = NULL,  n=1000)

p3b = dat.bites.sum %>% 
  modelr::data_grid(bite_on, habitat, site) %>% 
  add_fitted_draws(mod.brms.bites3, re_formula = NULL,  n=1000) #%>% 
  mutate(habitat = factor(ifelse(habitat == "Reef crest", "Crest", "Flat"), 
                           levels = c("Crest", "Flat")))
  
 

p4 = dat.bites.sum %>%
  modelr::data_grid(bite_on, habitat, site) %>%
  # spread_draws()
  add_fitted_draws(mod.brms.bites3, re_formula = NULL, n=1000)  %>%
  compare_levels(.value, by = bite_on)

p3b = mod.brms.bites %>% emmeans(~ bite_on|habitat + site, type="response") %>%
  gather_emmeans_draws(type="response") %>%
  mutate(.value = exp(.value)) %>% 
  mutate(habitat = factor(ifelse(habitat == "Reef crest", "Crest", "Flat"), 
                           levels = c("Crest", "Flat"))) 

p4b = mod.brms.bites %>% emmeans(~ bite_on|habitat + site, type="response") %>%
  gather_emmeans_draws(type="response") %>%
  mutate(.value = exp(.value)) %>%
  compare_levels(.value, by = bite_on) %>%
  mutate(habitat = factor(ifelse(habitat == "Reef crest", "Crest", "Flat"), 
                           levels = c("Crest", "Flat")))  

 


p3.1a = ggplot(p3a, aes(y = .value, x = site, fill = bite_on)) +
  theme_bw(base_size = 12) + 
  coord_cartesian(ylim= c(0,400)) +
  geom_point(data=dat.bites.sum, aes(y=TotalBites, x=site, colour=bite_on), 
             position = position_jitterdodge(jitter.width = 0.1),pch=1) +
  stat_eye(alpha=0.7, position = position_dodge(width = 0.7), .width = c(0.5, 0.95)) +
  # stat_gradientinterval(position = "dodge") +
  # scale_y_continuous(breaks = c(0.25, 0.5,0.75,1,1.25), limits = c(0.25,1.5)) +
  scale_fill_manual(values=c("seagreen", "orange"),
                    labels = c("Algal turf with \nSargassum propagules", "Algal turf without \nSargassum propagules")) +
  scale_colour_manual(values=c("seagreen", "orange"),
                      labels = c("Algal turf with \nSargassum propagules", "Algal turf without \nSargassum propagules")) +
  # scale_fill_viridis_d() +
  # scale_y_log10() +
  # scale_colour_viridis_d() +
  theme(legend.position ="bottom",axis.title.x = element_blank()) +facet_grid(~habitat) +
  ylab("Proportion of progagules remaining")  
p3.1b = ggplot(p3b, aes(y = .value, x = site, fill = bite_on)) +
  theme_bw(base_size = 12) + 
  coord_cartesian(ylim= c(0,400)) +
  geom_point(data=dat.bites.sum, aes(y=TotalBites, x=site, colour=bite_on), 
             position = position_jitterdodge(jitter.width = 0.1),pch=1) +
  stat_eye(alpha=0.7, position = position_dodge(width = 0.7), .width = c(0.5, 0.95),point_interval=median_hdi) +
  # stat_pointinterval(alpha=0.7, position = position_dodge(width = 0.7), .width = c(0.5, 0.95),
  #                    point_interval=median_hdi) +
  # stat_gradientinterval(position = "dodge") +
  # scale_y_continuous(breaks = c(0.25, 0.5,0.75,1,1.25), limits = c(0.25,1.5)) +
  scale_fill_manual(values=c("seagreen", "orange"),
                    labels = c("Algal turf with \nSargassum propagules", "Algal turf without \nSargassum propagules")) +
  scale_colour_manual(values=c("seagreen", "orange"),
                      labels = c("Algal turf with \nSargassum propagules", "Algal turf without \nSargassum propagules")) +
  # scale_fill_viridis_d() +
  # scale_y_log10() +
  # scale_colour_viridis_d() +
  theme(legend.position = "bottom",axis.title.x = element_blank(), legend.margin=margin(-10, 0, 0, 0),
        axis.title.y = element_text(family="sans"),legend.title = element_blank()) +facet_grid(~habitat) +
  ylab(expression(Number~of~bites~hr^{"-1"}~"+/-"~"95% credible intervals"))

p4.1  = ggplot(p4b, aes(x = .value/3, y = site)) +
  stat_pointinterval(alpha=0.7, position = position_dodge(width = 0.7), .width = c(0.5, 0.95),
                     point_interval=median_qi) +
  theme_bw(base_size = 12) + geom_vline(xintercept=0, linetype="dashed") +
  # scale_y_continuous(breaks = c(0.25, 0.5,0.75,1,1.25), limits = c(0.25,1.5)) +
  # scale_x_log10() +
  scale_y_discrete(limits=rev) +
  theme(legend.position = "right", axis.title.y = element_blank(),
        legend.margin=margin(-13, 0, 0, 0)) +facet_wrap(~habitat, ncol = 1) +
  xlab("Difference in Bites \n(Turf-Propagules)")
g = egg::ggarrange(p3.1b, p4.1, ncol=2, widths = c(1.4,1))
ggsave("Figures/Grazing.png", plot = g, device = "png", 
       width = 6, height = 5, dpi=300)
ggsave("Figures/Grazing.tiff", plot = g, device = "tiff", 
       width = 6, height = 5, dpi=300)
ggsave("Figures/Grazing.svg", plot = g, device = "svg", 
       width = 6, height = 5, dpi=300)
emmeans::emmeans(mod.brms.bites,~ bite_on|habitat + site, type="response")
pairs(emmeans::emmeans(mod.brms.bites,~ bite_on, type="response"), reverse = T)
emmeans::emmeans(mod.brms.bites,~ habitat, type="response")
emmeans::emmeans(mod.brms.bites,~ site, type="response")
```

```{r Part 3 - Species Specific Grazing OLD}
dat.bites = read.csv("Data/Chapter 5 fish bites.csv")
colnames(dat.bites)[1] = "Date"
dat.bites.spsum = dat.bites %>% 
  # filter(!is.na(bites)) %>%
  group_by(Date, id, habitat, site, species, bite_on) %>%
  summarise(TotalBites = sum(bites, na.rm =T)) %>%
  mutate(id = factor(id), bite_on = factor(bite_on)) %>%
  spread(bite_on,TotalBites) %>% 
  select(-V3) %>%
  gather(bite_on, TotalBites, 6:7, na.rm = F) %>% arrange(Date, id, habitat, site, species) %>%
  dplyr::mutate(TotalBites = replace_na(TotalBites, 0)) %>%
  filter(species %in% c("Ecsenius stictus", "Ctenochaetus striatus"))
# 
dat.bites.gensum = dat.bites %>% 
  # filter(!is.na(bites)) %>%
  separate(species, into = c("Genus", "Species"), sep = " ") %>%
  group_by(Date, id, habitat, site, Genus, bite_on) %>%
  summarise(TotalBites = sum(bites, na.rm =T)) %>%
  mutate(id = factor(id), bite_on = factor(bite_on)) %>%
  spread(bite_on,TotalBites) %>% select(-V3) %>%
  gather(bite_on, TotalBites, 6:7, na.rm = F) %>% arrange(Date, id, habitat, site, Genus) %>%
  dplyr::mutate(TotalBites = replace_na(TotalBites, 0)) %>%
  filter(Genus %in% c("Scarus", "Acanthurus", "Pomacentrus")) %>%
  rename("species" ="Genus" )

dat.bites.spmod1 = bind_rows(dat.bites.gensum, dat.bites.spsum) %>%
  filter(species %in% c("Pomacentrus","Ecsenius stictus"))
dat.bites.spmod2 = bind_rows(dat.bites.gensum, dat.bites.spsum) %>%
  filter(!species %in% c("Pomacentrus","Ecsenius stictus"))
dat.bites.spmod = bind_rows(dat.bites.spmod1, dat.bites.spmod2) %>%
  mutate(habitat = factor(ifelse(habitat == "Reef crest", "Crest", "Flat"), 
                           levels = c("Crest", "Flat")))

mod.brms.bitessp1 = brm(formula =TotalBites ~ bite_on*species*habitat + site +(1|Date), 
                    data=dat.bites.spmod1, family="negbinomial", sample_prior = T,
                    prior = c(prior(normal(0, 5), class = "Intercept"),
                              prior(normal(0, 5), class = "b"),
                              prior(normal(0,5), class = "sd"), 
                              prior(gamma(0.1, 0.1), class = "shape")),
                    warmup = 200, iter = 2000, chains = 3, cores = 3, thin=2,
                    control = list(adapt_delta = 0.95))
                    #                max_treedepth=15)
                    # )
mod.brms.bitessp2 = brm(formula =TotalBites ~ bite_on*species + site + (1|Date), 
                    data=dat.bites.spmod2, family="negbinomial", sample_prior = T,
                    prior = c(prior(normal(0, 5), class = "Intercept"),
                              prior(normal(0, 5), class = "b"),
                              prior(normal(0,5), class = "sd"), 
                              prior(gamma(0.1, 0.1), class = "shape")),
                    warmup = 200, iter = 2000, chains = 3, cores = 3, thin=2,
                    control = list(adapt_delta = 0.9))


mod_em = emmeans::emmeans(mod.brms.bitessp,~ bite_on|species)
mod_em
summary(pairs(mod_em), type = "response")
multcomp::cld(mod_em)
# perf.brms1 = performance::check_model(mod.brms.surv)
summary(mod.brms.bites)
p5 = dat.bites.spmod1 %>%
  modelr::data_grid(bite_on, species, habitat, site) %>%
  add_fitted_draws(mod.brms.bitessp1, re_formula = NULL,  n=100) 
p6 = dat.bites.spmod1 %>%
  modelr::data_grid(bite_on,species, habitat, site) %>%
  # spread_draws()
  add_fitted_draws(mod.brms.bitessp1, re_formula = NULL, n=100)  %>%
  compare_levels(.value, by = bite_on) %>%
  mutate(.value = .value/3)

p5.1 = ggplot(p5, aes(y = (.value/3), x=habitat, fill = bite_on, shape=bite_on)) +
  theme_bw(base_size = 12) + 
  # coord_cartesian(ylim= c(0,600)) +
  geom_point(data=dat.bites.spmod1, aes(y=(TotalBites/3), x=habitat, colour=bite_on), position = position_jitterdodge(),pch=1) +
  stat_pointinterval(alpha=0.7, position = position_dodge(width = 0.7), .width = c(0.5, 0.95)) +
  # stat_gradientinterval(position = "dodge") +
  # scale_y_continuous(breaks = c(0.25, 0.5,0.75,1,1.25), limits = c(0.25,1.5)) +
  scale_fill_viridis_d() +
  # scale_y_log10() +
  scale_colour_viridis_d() +
  theme(legend.position = "bottom",axis.title.x = element_blank()) +
  facet_wrap(~species, scales = "free_y", ncol = 1) +
  ylab("Proportion of progagules remaining")   

p6.1 = ggplot(p6, aes(x = .value, y = habitat)) +
  # stat_ccdfinterval(alpha=0.7, position = position_dodge(width = 0.7), .width = c(0.5, 0.95),side = "bottom") +
  # stat_interval(alpha=0.7,.width = c(.50, .80, .95, .99)) +
  # stat_interval(alpha=0.7, position = position_dodge(width = 0.7), .width = c(0.5, 0.95),side = "bottom") +
  stat_pointinterval(alpha=0.7, position = position_dodge(width = 0.7), .width = c(0.5, 0.95),side = "bottom") +
  theme_bw(base_size = 12) + 
  # geom_hline(yintercept=0, linetype="dashed") +
  # scale_y_continuous(breaks = c(0.25, 0.5,0.75,1,1.25), limits = c(0.25,1.5)) +
  # scale_x_log10() +
  theme(legend.position = "right", axis.title.y = element_blank(),axis.text.y = element_blank()) +
  facet_wrap(~species, scales="free", ncol=1) +
  # coord_cartesian(xlim = c(-20,500)) +
  # geom_vline(xintercept=0, linetype="dashed") +
  # facet_wrap(~habitat, ncol = 1) +
  ylab("Difference in proportion of propagules \nremaining (Caged-Exposed)")
egg::ggarrange(p5.1, p6.1, ncol=2, widths = c(1.2,1))

```

```{r Part 3 - Species Specific Grazing}

dat.bites.spmodCS =  dat.bites.spmod %>% 
  filter(species =="Ctenochaetus striatus") %>% 
  mutate(TotalBites = round(TotalBites/3,0))
dat.bites.spmodCS2 =  dat.bites.spmodCS %>% right_join(select(dat.bites.sum, -TotalBites)) %>%
  mutate(species = "Ctenochaetus striatus", 
         TotalBites = replace_na(TotalBites, replace = 0))%>%
  filter(habitat == "Crest")
  
dat.bites.spmodSc =  dat.bites.spmod %>% filter(species =="Scarus")%>% 
  mutate(TotalBites = round(TotalBites/3,0))
dat.bites.spmodSC2 =  dat.bites.spmodSc %>% right_join(select(dat.bites.sum, -TotalBites)) %>%
  mutate(species = "Scarus", 
         TotalBites = replace_na(TotalBites, replace = 0)) %>%
  filter(habitat == "Crest")
dat.bites.spmodAC =  dat.bites.spmod %>% filter(species =="Acanthurus")%>% 
  mutate(TotalBites = round(TotalBites/3,0))
dat.bites.spmodAC2 =  dat.bites.spmodAC %>% right_join(select(dat.bites.sum, -TotalBites)) %>%
  mutate(species = "Acanthurus", 
         TotalBites = replace_na(TotalBites, replace = 0)) %>%
  filter(habitat == "Crest")
dat.bites.spmodES =  dat.bites.spmod %>% filter(species =="Ecsenius stictus")%>% 
  mutate(TotalBites = round(TotalBites/3,0))
dat.bites.spmodES2 =  dat.bites.spmodES %>% right_join(select(dat.bites.sum, -TotalBites)) %>%
  mutate(species = "Ecsenius stictus", 
         TotalBites = replace_na(TotalBites, replace = 0))
dat.bites.spmodPO =  dat.bites.spmod %>% filter(species =="Pomacentrus")%>% 
  mutate(TotalBites = round(TotalBites/3,0))
dat.bites.spmodPO2 =  dat.bites.spmodPO %>% right_join(select(dat.bites.sum, -TotalBites)) %>%
  mutate(species = "Pomacentrus", 
         TotalBites = replace_na(TotalBites, replace = 0))


mod.brms.bitesspCS = brm(formula =TotalBites ~ bite_on + site + (1|id/Date), 
                    data=dat.bites.spmodCS, family="negbinomial", sample_prior = T,
                    prior = c(prior(normal(0, 5), class = "Intercept"),
                              prior(normal(0, 5), class = "b"),
                              prior(normal(0,5), class = "sd"), 
                              prior(gamma(0.1, 0.1), class = "shape")),
                    warmup = 200, iter = 2000, chains = 3, cores = 3, thin=2,
                    control = list(adapt_delta = 0.95))
mod.brms.bitesspCS.2 = brm(formula =TotalBites ~ bite_on + site + (1|id/Date), 
                    data=dat.bites.spmodCS2, family="negbinomial", sample_prior = T,
                    prior = c(prior(normal(0, 5), class = "Intercept"),
                              prior(normal(0, 5), class = "b"),
                              prior(normal(0,5), class = "sd"), 
                              prior(gamma(0.1, 0.1), class = "shape")),
                    warmup = 200, iter = 2000, chains = 3, cores = 3, thin=2,
                    control = list(adapt_delta = 0.98))
mod.brms.bitesspSc = brm(formula =TotalBites ~ bite_on + site + (1|id/Date), 
                    data=dat.bites.spmodSc, family="negbinomial", sample_prior = T,
                    prior = c(prior(normal(0, 5), class = "Intercept"),
                              prior(normal(0, 5), class = "b"),
                              prior(normal(0,5), class = "sd"), 
                              prior(gamma(0.1, 0.1), class = "shape")),
                    warmup = 200, iter = 2000, chains = 3, cores = 3, thin=2,
                    control = list(adapt_delta = 0.99))
mod.brms.bitesspSc.2 = brm(formula =TotalBites ~ bite_on + site + (1|id/Date), 
                    data=dat.bites.spmodSC2, family="negbinomial", sample_prior = T,
                    prior = c(prior(normal(0, 5), class = "Intercept"),
                              prior(normal(0, 5), class = "b"),
                              prior(normal(0,5), class = "sd"), 
                              prior(gamma(0.1, 0.1), class = "shape")),
                    warmup = 200, iter = 2000, chains = 3, cores = 3, thin=2,
                    control = list(adapt_delta = 0.99))
mod.brms.bitesspAC = brm(formula =TotalBites ~ bite_on, 
                    data=dat.bites.spmodAC, family="negbinomial", sample_prior = T,
                    prior = c(prior(normal(0, 5), class = "Intercept"),
                              prior(normal(0, 5), class = "b"),
                              # prior(normal(0,5), class = "sd"), 
                              prior(gamma(0.1, 0.1), class = "shape")),
                    warmup = 200, iter = 2000, chains = 3, cores = 3, thin=2,
                    control = list(adapt_delta = 0.99))
mod.brms.bitesspAC.2 = brm(formula =TotalBites ~ bite_on, 
                    data=dat.bites.spmodAC2, family="negbinomial", sample_prior = T,
                    prior = c(prior(normal(0, 5), class = "Intercept"),
                              prior(normal(0, 5), class = "b"),
                              # prior(normal(0,5), class = "sd"), 
                              prior(gamma(0.1, 0.1), class = "shape")),
                    warmup = 200, iter = 2000, chains = 3, cores = 3, thin=2,
                    control = list(adapt_delta = 0.99))
mod.brms.bitesspES = brm(formula =TotalBites ~ bite_on*habitat + site + (1|id/Date), 
                    data=dat.bites.spmodES, family="negbinomial", sample_prior = T,
                    prior = c(prior(normal(0, 5), class = "Intercept"),
                              prior(normal(0, 5), class = "b"),
                              prior(normal(0,5), class = "sd"), 
                              prior(gamma(0.1, 0.1), class = "shape")),
                    warmup = 200, iter = 2000, chains = 3, cores = 3, thin=2,
                    control = list(adapt_delta = 0.99, max_treedepth=12))
mod.brms.bitesspES.2 = brm(formula =TotalBites ~ bite_on*habitat + site + (1|id/Date), 
                    data=dat.bites.spmodES2, family="negbinomial", sample_prior = T,
                    prior = c(prior(normal(0, 5), class = "Intercept"),
                              prior(normal(0, 5), class = "b"),
                              prior(normal(0,5), class = "sd"), 
                              prior(gamma(0.1, 0.1), class = "shape")),
                    warmup = 200, iter = 2000, chains = 3, cores = 3, thin=2,
                    control = list(adapt_delta = 0.99, max_treedepth=12))
mod.brms.bitesspPO = brm(formula =TotalBites ~ bite_on*habitat + site + (1|id/Date), 
                    data=dat.bites.spmodPO, family="negbinomial", sample_prior = T,
                    prior = c(prior(normal(0, 5), class = "Intercept"),
                              prior(normal(0, 5), class = "b"),
                              prior(normal(0,5), class = "sd"), 
                              prior(gamma(0.1, 0.1), class = "shape")),
                    warmup = 200, iter = 2000, chains = 3, cores = 3, thin=2,
                    control = list(adapt_delta = 0.98))
mod.brms.bitesspPO.2 = brm(formula =TotalBites ~ bite_on*habitat + site + (1|id/Date), 
                    data=dat.bites.spmodPO2, family="negbinomial", sample_prior = T,
                    prior = c(prior(normal(0, 5), class = "Intercept"),
                              prior(normal(0, 5), class = "b"),
                              prior(normal(0,5), class = "sd"), 
                              prior(gamma(0.1, 0.1), class = "shape")),
                    warmup = 200, iter = 2000, chains = 3, cores = 3, thin=2,
                    control = list(adapt_delta = 0.98))
mod_emCS2 = emmeans::emmeans(mod.brms.bitesspCS.2,~ bite_on, type="response")
mod_emES2 = emmeans::emmeans(mod.brms.bitesspES.2,~ bite_on|habitat, type="response")
mod_emPO2 = emmeans::emmeans(mod.brms.bitesspPO.2,~ bite_on|habitat, type="response")

pairs(emmeans::emmeans(mod.brms.bitesspES.2,~ bite_on, type="response"), reverse = T)
pairs(emmeans::emmeans(mod.brms.bitesspPO.2,~ bite_on, type="response"), reverse = T)

emmeans::emmeans(mod.brms.bitesspES.2,~ habitat, type="response")
emmeans::emmeans(mod.brms.bitesspPO.2,~ habitat, type="response")
emmeans::emmeans(mod.brms.bitesspCS.2,~ bite_on, type="response")
# Ctenochaetus striatus ----
pCS1 = dat.bites.spmodCS %>%
  modelr::data_grid(bite_on, species, site) %>%
  add_fitted_draws(mod.brms.bitesspCS, re_formula = NULL,  n=1000) 
pCS1.1 = dat.bites.spmodCS %>%
  modelr::data_grid(bite_on, species, site) %>%
  add_fitted_draws(mod.brms.bitesspCS, re_formula = NULL,  n=1000) %>% group_by(bite_on)%>%
  median_hdi(.value)

pCS2 = dat.bites.spmodCS %>%
  modelr::data_grid(bite_on,species, site) %>%
  add_fitted_draws(mod.brms.bitesspCS, re_formula = NULL, n=100)  %>%
  compare_levels(.value, by = bite_on) 

pCSa = mod.brms.bitesspCS.2 %>% emmeans(~ bite_on, type="response") %>%
  gather_emmeans_draws(type="response") %>%
  mutate(.value = exp(.value), habitat="Crest")

pCSb = pCSa %>% compare_levels(.value, by = bite_on) %>%
  mutate(species = "Ctenochaetus striatus", habitat="Crest")

pCS.1 = ggplot(pCSa, aes(y = (.value), x=habitat, fill = bite_on)) +
  theme_bw(base_size = 12) +
  stat_eye(alpha=0.7, position = position_dodge(width = 0.7), .width = c(0.5, 0.95)) +
  coord_cartesian(ylim= c(0,10)) +
  geom_point(data=dat.bites.spmodCS2, aes(y=(TotalBites), x=habitat, colour=bite_on), 
             position = position_jitterdodge(jitter.width = 0.1),pch=1) +
  stat_pointinterval(alpha=0.7, position = position_dodge(width = 0.7), .width = c(0.66, 0.95)) +
  # stat_gradientinterval(position = "dodge") +
  # scale_y_continuous(breaks = c(0.25, 0.5,0.75,1,1.25), limits = c(0.25,1.5)) +
   scale_fill_manual(values=c("seagreen", "orange"),
                    labels = c("Algal turf with \nSargassum propagules", "Algal turf without \nSargassum propagules")) +
  scale_colour_manual(values=c("seagreen", "orange"),
                      labels = c("Algal turf with \nSargassum propagules", "Algal turf without \nSargassum propagules")) +
  # scale_fill_manual(values=c("seagreen", "orange")) +
  # scale_colour_manual(values=c("seagreen", "orange")) +
  # scale_fill_viridis_d() +
  # scale_y_log10() +
  # scale_colour_viridis_d() +
  theme(legend.position = "bottom",legend.title = element_blank(),
        axis.title.x = element_blank(),axis.title.y = element_blank(),
        legend.margin=margin(-13, 0, 0, 0)) +
  facet_wrap(~species, scales = "free_y", ncol = 1)

pCS.2 = ggplot(pCSb, aes(x = .value, y = habitat)) +
  # stat_eye(alpha=0.7, position = position_dodge(width = 0.7), .width = c(0.5, 0.95),side = "bottom") +
  # stat_interval(alpha=0.7,.width = c(.50, .80, .95, .99)) +
  # stat_interval(alpha=0.7, position = position_dodge(width = 0.7), .width = c(0.5, 0.95),side = "bottom") +
  stat_pointinterval(alpha=0.7, position = position_dodge(width = 0.7), .width = c(0.66, 0.95)) +
  theme_bw(base_size = 12) + 
  geom_vline(xintercept=0, linetype="dashed") +
  # scale_y_continuous(breaks = c(0.25, 0.5,0.75,1,1.25), limits = c(0.25,1.5)) +
  # scale_x_log10() +
  theme(legend.position = "right", axis.title.y = element_blank(),axis.text.y = element_blank()) +
  facet_wrap(~species, scales="free", ncol=1) + 
  xlab("Difference in Bites \n(Turf-Propagules)")
  # coord_cartesian(xlim = c(-20,500)) +
  # geom_vline(xintercept=0, linetype="dashed") +
  # facet_wrap(~habitat, ncol = 1) +
  
egg::ggarrange(pCS.1, pCS.2, ncol=2, widths = c(1.2,1))

# Scarus----
pSC1 = dat.bites.spmodSc %>%
  modelr::data_grid(bite_on, species, site) %>%
  add_fitted_draws(mod.brms.bitesspSc, re_formula = NULL,  n=1000) %>%
  mutate(.value = .value/3)
pSC2 = dat.bites.spmodSc %>%
  modelr::data_grid(bite_on,species, site) %>%
  add_fitted_draws(mod.brms.bitesspSc, re_formula = NULL, n=100)  %>%
  compare_levels(.value, by = bite_on) %>%
  mutate(.value = .value/3)
pSCa = mod.brms.bitesspSc.2 %>% emmeans(~ bite_on, type="response") %>%
  gather_emmeans_draws(type="response") %>%
  mutate(.value = exp(.value), habitat="Crest")

pSCb = pSCa %>% compare_levels(.value, by = bite_on) %>%
  mutate(species = "Scarus", habitat="Crest")
pSC.1 = ggplot(pSCa, aes(y = (.value), x=habitat, fill = bite_on)) +
  theme_bw(base_size = 12) +
  stat_eye(alpha=0.7, position = position_dodge(width = 0.7), .width = c(0.5, 0.95)) +
  coord_cartesian(ylim= c(0,1)) +
  geom_point(data=dat.bites.spmodSC2, aes(y=(TotalBites/3), x=habitat, colour=bite_on), 
             position = position_jitterdodge(jitter.width = 0.1),pch=1) +
  stat_pointinterval(alpha=0.7, position = position_dodge(width = 0.7), .width = c(0.66, 0.95)) +
  # stat_gradientinterval(position = "dodge") +
  # scale_y_continuous(breaks = c(0.25, 0.5,0.75,1,1.25), limits = c(0.25,1.5)) +
  scale_fill_manual(values=c("seagreen", "orange")) +
  scale_colour_manual(values=c("seagreen", "orange")) +
  # scale_fill_viridis_d() +
  # scale_y_log10() +
  # scale_colour_viridis_d() +
  theme(legend.position = "none",axis.title.x = element_blank(),axis.title.y = element_text(family="sans")) +
  facet_wrap(~species, scales = "free_y", ncol = 1) +
  ylab(expression(Number~of~bites~hr^{"-1"}~"\U00B1"~"95% quantile intervals"))  

pSC.2 = ggplot(pSCb, aes(x = .value, y = habitat)) +
  # stat_eye(alpha=0.7, position = position_dodge(width = 0.7), .width = c(0.5, 0.95),side = "bottom") +
  # stat_interval(alpha=0.7,.width = c(.50, .80, .95, .99)) +
  # stat_interval(alpha=0.7, position = position_dodge(width = 0.7), .width = c(0.5, 0.95),side = "bottom") +
  stat_pointinterval(alpha=0.7, .width = c(0.66, 0.95)) +
  theme_bw(base_size = 12) + 
  geom_vline(xintercept=0, linetype="dashed") +
  # scale_y_continuous(breaks = c(0.25, 0.5,0.75,1,1.25), limits = c(0.25,1.5)) +
  # scale_x_log10() +
  theme(legend.position = "right", axis.title.y = element_blank(),axis.text.y = element_blank(),
        axis.title.x = element_blank()) +
  facet_wrap(~species, scales="free", ncol=1) 
  # coord_cartesian(xlim = c(-20,500)) +
  # geom_vline(xintercept=0, linetype="dashed") +
  # facet_wrap(~habitat, ncol = 1) +
  # ylab("Difference in proportion of propagules \nremaining (Caged-Exposed)")

egg::ggarrange(pSC.1, pSC.2, ncol=2, widths = c(1.2,1))

# Acanthurus----
pAC1 = dat.bites.spmodAC %>%
  modelr::data_grid(bite_on, species, site) %>%
  add_fitted_draws(mod.brms.bitesspAC, re_formula = NULL,  n=1000) %>%
  mutate(.value = .value/3)
pAC2 = dat.bites.spmodAC %>%
  modelr::data_grid(bite_on,species, site) %>%
  add_fitted_draws(mod.brms.bitesspAC, re_formula = NULL, n=100)  %>%
  compare_levels(.value, by = bite_on) %>%
  mutate(.value = .value/3)
pACa = mod.brms.bitesspAC.2 %>% emmeans(~ bite_on, type="response") %>%
  gather_emmeans_draws(type="response") %>%
  mutate(.value = exp(.value), habitat="Crest")

pACb = pACa %>% compare_levels(.value, by = bite_on) %>%
  mutate(species = "Acanthurus", habitat="Crest")

pAC.1 = ggplot(pACa, aes(y = (.value), x=habitat, fill = bite_on)) +
  theme_bw(base_size = 12) +
  stat_eye(alpha=0.7, position = position_dodge(width = 0.7), .width = c(0.5, 0.95)) +
  coord_cartesian(ylim= c(0,50)) +
  geom_point(data=dat.bites.spmodAC2, aes(y=(TotalBites/3), x=habitat, colour=bite_on), 
             position = position_jitterdodge(jitter.width = 0.1),pch=1) +
  stat_pointinterval(alpha=0.7, position = position_dodge(width = 0.7), .width = c(0.66, 0.95)) +
  # stat_gradientinterval(position = "dodge") +
  # scale_y_continuous(breaks = c(0.25, 0.5,0.75,1,1.25), limits = c(0.25,1.5)) +
  scale_fill_manual(values=c("seagreen", "orange"),
                    labels = c("Algal turf with \nSargassum propagules", "Algal turf without \nSargassum propagules")) +
  scale_colour_manual(values=c("seagreen", "orange"),
                      labels = c("Algal turf with \nSargassum propagules", "Algal turf without \nSargassum propagules")) +
  # scale_fill_viridis_d() +
  # scale_y_log10() +
  # scale_colour_viridis_d() +
  theme(legend.position = "bottom",legend.title = element_blank(),
        axis.title.x = element_blank(),axis.title.y = element_blank(),
        legend.margin=margin(-13, 0, 0, 0)) +
  facet_wrap(~species, scales = "free_y", ncol = 1) 
  # ylab("Bites hr^-1")   

pAC.2 = ggplot(pACb, aes(x = .value, y = habitat)) +
  # stat_eye(alpha=0.7, position = position_dodge(width = 0.7), .width = c(0.5, 0.95),side = "bottom") +
  # stat_interval(alpha=0.7,.width = c(.50, .80, .95, .99)) +
  # stat_interval(alpha=0.7, position = position_dodge(width = 0.7), .width = c(0.5, 0.95),side = "bottom") +
  stat_pointinterval(alpha=0.7, .width = c(0.66, 0.95)) +
  theme_bw(base_size = 12) + 
  geom_vline(xintercept=0, linetype="dashed") +
  # scale_y_continuous(breaks = c(0.25, 0.5,0.75,1,1.25), limits = c(0.25,1.5)) +
  # scale_x_log10() +
  theme(legend.position = "none", axis.title.y = element_blank(),axis.text.y = element_blank()) +
  facet_wrap(~species, scales="free", ncol=1) +
  # coord_cartesian(xlim = c(-20,500)) +
  # geom_vline(xintercept=0, linetype="dashed") +
  # facet_wrap(~habitat, ncol = 1) +
  xlab("Difference in Bites \n(Turf-Propagules)")

egg::ggarrange(pCS.1, pCS.2,pSC.1, pSC.2, pAC.1,pAC.2,ncol=2, widths = c(1.2,1))
```

```{r}
# Ecsenius stictus---
pES1 = dat.bites.spmodES %>%
  modelr::data_grid(bite_on, species,habitat, site) %>%
  add_fitted_draws(mod.brms.bitesspES, re_formula = NULL,  n=1000) %>%
  mutate(.value = .value/3)
pES2 = dat.bites.spmodES %>%
  modelr::data_grid(bite_on,species, habitat, site) %>%
  add_fitted_draws(mod.brms.bitesspES, re_formula = NULL, n=100)  %>%
  compare_levels(.value, by = bite_on) %>%
  mutate(.value = .value/3)
pESa = mod.brms.bitesspES.2 %>% emmeans(~ bite_on|habitat, type="response") %>%
  gather_emmeans_draws(type="response") %>%
  mutate(.value = exp(.value))

pESb = pESa %>% compare_levels(.value, by = bite_on) %>%
  mutate(species = "Ecsenius stictus")

pES.1 = ggplot(pESa, aes(y = (.value), x=habitat, fill = bite_on)) +
  theme_bw(base_size = 12) +
  stat_eye(alpha=0.7, position = position_dodge(width = 0.7), .width = c(0.5, 0.95)) +
  coord_cartesian(ylim= c(0,350)) +
  geom_point(data=dat.bites.spmodES2, aes(y=(TotalBites/3), x=habitat, colour=bite_on), 
             position = position_jitterdodge(jitter.width = 0.1),pch=1) +
  stat_pointinterval(alpha=0.7, position = position_dodge(width = 0.7), .width = c(0.66, 0.95)) +
  # stat_gradientinterval(position = "dodge") +
  # scale_y_continuous(breaks = c(0.25, 0.5,0.75,1,1.25), limits = c(0.25,1.5)) +
   scale_fill_manual(values=c("seagreen", "orange")) +
  scale_colour_manual(values=c("seagreen", "orange")) +
  # scale_fill_viridis_d() +
  # scale_y_log10() +
  # scale_colour_viridis_d() +
  theme(legend.position = "none",axis.title.x = element_blank(),axis.title.y = element_blank()) +
  facet_wrap(~species, scales = "free_y", ncol = 1) 
  # ylab("Bites hr^-1")   

pES.2 = ggplot(pESb, aes(x = .value, y = habitat)) +
  # stat_eye(alpha=0.7, position = position_dodge(width = 0.7), .width = c(0.5, 0.95),side = "bottom") +
  # stat_interval(alpha=0.7,.width = c(.50, .80, .95, .99)) +
  # stat_interval(alpha=0.7, position = position_dodge(width = 0.7), .width = c(0.5, 0.95),side = "bottom") +
  stat_pointinterval(alpha=0.7, .width = c(0.66, 0.95)) +
  theme_bw(base_size = 12) + 
  geom_vline(xintercept=0, linetype="dashed") +
  # scale_y_continuous(breaks = c(0.25, 0.5,0.75,1,1.25), limits = c(0.25,1.5)) +
  # scale_x_log10() +
  theme(legend.position = "none", axis.title.y = element_blank(),axis.text.y = element_blank(),
        axis.title.x = element_blank()) +
  facet_grid(habitat~species, scales = "free")

egg::ggarrange(pES.1, pES.2,ncol=2, widths = c(1.2,1))

# POmacentrus---
pPO1 = dat.bites.spmodPO %>%
  modelr::data_grid(bite_on, species,habitat, site) %>%
  add_fitted_draws(mod.brms.bitesspPO, re_formula = NULL,  n=1000) %>%
  mutate(.value = .value/3)
pPO2 = dat.bites.spmodPO %>%
  modelr::data_grid(bite_on,species, habitat, site) %>%
  add_fitted_draws(mod.brms.bitesspPO, re_formula = NULL, n=100)  %>%
  compare_levels(.value, by = bite_on) %>%
  mutate(.value = .value/3)
pPOa = mod.brms.bitesspPO.2 %>% emmeans(~ bite_on|habitat, type="response") %>%
  gather_emmeans_draws(type="response") %>%
  mutate(.value = exp(.value))

pPOb = pPOa %>% compare_levels(.value, by = bite_on) %>%
  mutate(species = "Pomacentrus")
pPO.1 = ggplot(pPOa, aes(y = (.value), x=habitat, fill = bite_on)) +
  theme_bw(base_size = 12) +
  stat_eye(alpha=0.7, position = position_dodge(width = 0.7), .width = c(0.5, 0.95)) +
  coord_cartesian(ylim= c(0,2)) +
  geom_point(data=dat.bites.spmodPO2, aes(y=(TotalBites/3), x=habitat, colour=bite_on), 
             position = position_jitterdodge(jitter.width = 0.1),pch=1) +
  stat_pointinterval(alpha=0.7, position = position_dodge(width = 0.7), .width = c(0.66, 0.95)) +
  # stat_gradientinterval(position = "dodge") +
  # scale_y_continuous(breaks = c(0.25, 0.5,0.75,1,1.25), limits = c(0.25,1.5)) +
  # scale_fill_viridis_d() +
  scale_fill_manual(values=c("seagreen", "orange")) +
  scale_colour_manual(values=c("seagreen", "orange")) +
  # scale_y_log10() +
  # scale_colour_viridis_d() +
  theme(legend.position = "none",axis.title.x = element_blank(),
        legend.margin=margin(-13, 0, 0, 0)) +
  facet_wrap(~species, scales = "free_y", ncol = 1) +
  ylab(expression(Number~of~bites~hr^{"-1"}~"+/-"~"95% credible intervals")) 
  # ylab("Bites hr^-1")   

pPO.2 = ggplot(pPOb, aes(x = .value, y = habitat)) +
  # stat_eye(alpha=0.7, position = position_dodge(width = 0.7), .width = c(0.5, 0.95),side = "bottom") +
  # stat_interval(alpha=0.7,.width = c(.50, .80, .95, .99)) +
  # stat_interval(alpha=0.7, position = position_dodge(width = 0.7), .width = c(0.5, 0.95),side = "bottom") +
  stat_pointinterval(alpha=0.7, .width = c(0.66, 0.95)) +
  theme_bw(base_size = 12) + 
  geom_vline(xintercept=0, linetype="dashed") +
  # scale_y_continuous(breaks = c(0.25, 0.5,0.75,1,1.25), limits = c(0.25,1.5)) +
  # scale_x_log10() +
  theme(legend.position = "none", axis.title.y = element_blank(),axis.text.y = element_blank(),
        axis.title.x = element_blank()) +
  facet_grid(habitat~species, scales = "free") #+
  # coord_cartesian(xlim = c(-20,500)) +
  # geom_vline(xintercept=0, linetype="dashed") +
  # facet_wrap(~habitat, ncol = 1) +
  # xlab("Difference in Bites (Turf-Propagules)")
egg::ggarrange(pCS.1, pCS.2,pSC.1, pSC.2, pAC.1,pAC.2,ncol=2, widths = c(1.2,1))
g = egg::ggarrange(pES.1, pES.2,pPO.1, pPO.2,
                pCS.1, pCS.2,ncol=2,nrow = 3, widths = c(1.4,1),heights = c(1.5, 1.5,1))

ggsave("Figures/GrazingSpecies.png", plot = g, device = "png", 
       width = 6, height = 8, dpi=300)
ggsave("Figures/GrazingSpecies.tiff", plot = g, device = "tiff", 
       width = 6, height = 8, dpi=300)
ggsave("Figures/GrazingSpecies.svg", plot = g, device = "svg", 
       width = 6, height = 8, dpi=300)
svg("Figures/GrazingSpecies.svg")
print(g)     # Plot 1 --> in the first page of PDF     # Plot 2 ---> in the second page of the PDF
dev.off()
CS.Sum = dat.bites.spmodCS %>%
  modelr::data_grid(bite_on, species, site) %>%
  add_fitted_draws(mod.brms.bitesspCS, re_formula = NULL,  n=1000) %>% mutate(.value = .value/3)%>%
  group_by(bite_on) %>%
  median_qi(.value)
```

```{r Benthic Surveys}
dat.benth = readxl::read_xlsx("Data/Oct 17 benthic surveys.xlsx", sheet=2)
dat.benth = dat.benth %>%
  mutate(BenthosSum = ifelse(Benthos %in% c("Hard Coral", "Porites", "Juvenile coral"), "Hard Coral",
                      ifelse(Benthos %in% c("Turbinaria", "Halimeda", "Dictyosphaeria"), "Macroalgae",
                      ifelse(Benthos %in% c("Sand", "Rubble"), "Sand/Rubble",
                      ifelse(Benthos == "CCA", "CCA", ifelse(Benthos=="Turf", "Turf", "Other"))))),
         Site= recode(Site, Bird = "Site 1", South= "Site 2"))
dat.benthsum = dat.benth %>% 
  group_by(Habitat, Site, BenthosSum) %>% summarise(Count = n()) %>%
  mutate(Perc = Count/300) #%>%
  group_by(Habitat, Site, BenthosSum) %>%
  summarise(mn = mean(Perc),
            no=n(),
            se = sd(Perc)/sqrt(n()))
dat.benthsum2 = dat.benth %>% 
  group_by(Habitat, Site,`Transect number` ,BenthosSum) %>% summarise(Count = n()) %>%
  mutate(Perc = Count/100) %>% select(-Count) %>%
  spread(BenthosSum,Perc) %>%
  gather(BenthosSum, Perc, 4:9,na.rm = F) %>% mutate(Perc = replace_na(Perc, 0)) %>%
  group_by(Habitat, Site, BenthosSum) %>%
  summarise(mn = mean(Perc),
            # no=n(Count>0),
            se = sd(Perc)/sqrt(n()))  
  
  
p=ggplot(dat.benthsum, aes(x=Site, y=Perc)) +geom_col(aes(fill=BenthosSum)) +facet_grid(~Habitat) + 
  scale_fill_viridis_d() +theme_bw()

pBenth = ggplot(dat.benthsum2, aes(x=Site, y=mn)) +
  geom_pointrange(aes(shape=BenthosSum, ymin=mn-se, ymax=mn+se), position = position_dodge(width=0.5)) +
  facet_grid(~Habitat) + scale_y_continuous(labels = scales::percent) +
  # scale_colour_viridis_d() +
  theme_bw() + ylab("Mean % benthic cover +/- SE") + theme(axis.title.x = element_blank()) +
  labs(shape="Benthos")
ggsave("Figures/Benthos.png", plot = p, device = "png", 
       width = 6, height = 6, dpi=300)
```

```{r Fish Surveys}
dat.fish = readxl::read_xlsx("Data/Oct 17 fish surveys.xlsx", sheet=4) %>%
  mutate(Species = `Fish species`,
         Count = Count/5,
         Site= recode(Site, Bird = "Site 1", South= "Site 2")) %>%
  separate(`Fish species`, into = c("Genus", "Species2"), sep = " ") 

dat.fish2 = readxl::read_xlsx("Data/Oct 17 fish surveys.xlsx", sheet="BenthicFish") %>%
  mutate(Species = `Fish species`,
         Site= recode(Site, Bird = "Site 1", South= "Site 2")) %>%
  separate(`Fish species`, into = c("Genus", "Species2"), sep = " ") %>%
  filter(!`Include (Y/N)` == "n") %>%
  mutate(Count = Count/2) %>% select(c(1:3, 6,8,10))
colnames(dat.fish2)[4] = "Genus"

dat.fishsum = dat.fish %>% 
  group_by(Species) %>% summarise(Count = sum(Count)) %>% top_n(10, Count) %>%
  pull(Species)
dat.fishsum2 = dat.fish %>%
  group_by(Habitat, Site,`Transect #` ,Species) %>% summarise(Count = sum(Count)) %>%
  # mutate(Perc = Count/100) %>% select(-Count) %>%
  spread(Species,Count) %>%
  gather(Species,Count, 4:33,na.rm = F) %>% mutate(Count = replace_na(Count, 0)) %>%
  filter(Species %in% dat.fishsum) %>%
  group_by(Habitat, Site, Species) %>%
  summarise(mn = mean(Count),
            # no=n(Count>0),
            se = sd(Count)/sqrt(n()))  

dat.fishgen = dat.fish %>% select(c(1:4,7:8)) %>% rbind(dat.fish2) %>%
  group_by(Genus) %>% summarise(Count = sum(Count)) %>% top_n(10, Count) %>%
  pull(Genus)
dat.fishgen2 = dat.fish %>% select(c(1:4,7:8)) %>% rbind(dat.fish2) %>%
  group_by(Habitat, Site,`Transect #` ,Genus) %>% summarise(Count = sum(Count)) %>%
  # mutate(Perc = Count/100) %>% select(-Count) %>%
  spread(Genus,Count) %>%
  gather(Genus,Count, 4:17,na.rm = F) %>% mutate(Count = replace_na(Count, 0)) %>%
  # filter(Genus %in% dat.fishgen) %>% 
  filter(!Genus %in% c("juv.", "Juv.", "Dark")) %>%
  # mutate(Genus = recode(Genus, Dark = "Dark Parrot")) %>%
  group_by(Habitat, Site, Genus) %>% 
  summarise(mn = mean(Count),
            # no=n(Count>0),
            se = sd(Count)/sqrt(n()))  

dat.fishgen2$Family = ifelse(dat.fishgen2$Genus %in% c("Acanthurus", "Ctenochaetus", "Naso", "Zebrasoma"), "Acanthuridae",
                      ifelse(dat.fishgen2$Genus %in% c("Chlorurus", "Scarus"), "Labridae: Scarini",
                      ifelse(dat.fishgen2$Genus %in% c("Ecsenius stictus", "other Blenniidae"), "Blenniidae",
                      ifelse(dat.fishgen2$Genus %in% c("Pomacentrus spp", "other Pomacentridae"), "Pomacentridae", "Siganidae"))))
dat.fishgen2$Facet = factor(ifelse(dat.fishgen2$Genus == "Pomacentrus spp", "Pomacentrus spp", "Other Species"),
                            levels = c("Pomacentrus spp", "Other Species"))
genusorder = dat.fishgen2 %>% ungroup %>% select(Genus, Family) %>% distinct() %>% arrange(Family) %>% pull(Genus)
dat.fishgen2$Genus = factor(dat.fishgen2$Genus, levels = genusorder)
p=ggplot(dat.benthsum, aes(x=Site, y=Perc)) +geom_col(aes(fill=BenthosSum)) +facet_grid(~Habitat) + 
  scale_fill_viridis_d() +theme_bw()

ggplot(dat.fishsum2, aes(x=Site, y=mn)) +
  geom_pointrange(aes(colour=Species, ymin=mn-se, ymax=mn+se), position = position_dodge(width=0.5)) +
  facet_grid(~Habitat) + 
  scale_colour_viridis_d() +
  theme_bw()

pFish = ggplot(dat.fishgen2, aes(x=Site, y=mn, shape=Family)) +
  geom_pointrange(aes(colour=Genus, shape=Family,  ymin=mn-se, ymax=mn+se), position = position_dodge(width=0.9)) +
  facet_grid(Facet~Habitat, scales = "free_y") + 
  scale_colour_viridis_d() +
  # scale_y_sqrt() +
  # scale_y_continuous(trans = scales::log_trans(base = 10)) +
  # scale_y_sqrt(breaks = c(1,10,25,50,100,200)) +
  theme_bw() + ylab("Mean Abundance per Transect +/- SE")

pFish2 = ggplot(dat.fishgen2, aes(x=Site, y=mn)) +
  geom_pointrange(aes(colour=Genus, ymin=mn-se, ymax=mn+se), position = position_dodge(width=0.5)) +
  facet_grid(~Habitat) +
  scale_colour_viridis_d() +
  # scale_y_sqrt(breaks = c(1,10,50,100,200)) +
  theme_bw() + ylab("Mean Abundance per 50m2 +/- SE")
g = egg::ggarrange(pBenth, pFish, ncol = 1, heights = c(1,1.4))
ggsave("Figures/BenthosFish.png", plot = g, device = "png", 
       width = 7, height = 9, dpi=300)

pFish3 = ggplot(dat.fishgen2, aes(x=Site, y=mn, shape=Family)) +
  geom_pointrange(aes(colour=Genus, shape=Family,  ymin=mn-se, ymax=mn+se), position = position_dodge(width=0.9)) +
  facet_grid(~Habitat, scales = "free_y") + 
  scale_colour_viridis_d() +
  # scale_y_sqrt() +
  scale_y_continuous(trans = scales::log_trans(base = 10)) +
  # scale_y_sqrt(breaks = c(1,10,25,50,100,200)) +
  theme_bw() + ylab(expression("Mean Abundance per 50"~m^{"2"}~"+/- SE"))

g1 = egg::ggarrange(pBenth, pFish3, ncol = 1, heights = c(1,1.4))
ggsave("Figures/BenthosFish2.png", plot = g1, device = "png", 
       width = 7, height = 9, dpi=300)
ggsave("Figures/BenthosFish2.tiff", plot = g1, device = "tiff", 
       width = 7, height = 9, dpi=300)
ggsave("Figures/BenthosFish2.svg", plot = g1, device = "svg", 
       width = 7, height = 9, dpi=300)
```